// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace ElecSales.Models
{
    // AccountClaims
    public partial class AccountClaimsConfiguration : EntityTypeConfiguration<AccountClaims>
    {
        public AccountClaimsConfiguration()
            : this("dbo")
        {
        }
 
        public AccountClaimsConfiguration(string schema)
        {
            ToTable(schema + ".AccountClaims");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName("Id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.UserId).HasColumnName("UserId").IsRequired().HasColumnType("int");
            Property(x => x.ClaimType).HasColumnName("ClaimType").IsOptional().HasColumnType("nvarchar");
            Property(x => x.ClaimValue).HasColumnName("ClaimValue").IsOptional().HasColumnType("nvarchar");

            // Foreign keys
            HasRequired(a => a.Accounts).WithMany(b => b.AccountClaims).HasForeignKey(c => c.UserId); // FK_dbo.AccountClaims_dbo.Accounts_UserId
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
