// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace ElecSales.Models
{
    // ADL300
    public partial class Adl300
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // name
        public decimal? CurrentTotalElectric { get; set; } // Current_Total_Electric
        public decimal? CurrentPeakElectricEnergy { get; set; } // Current_peak_electric_energy
        public decimal? CurrentFloatElectricEnergy { get; set; } // Current_float_electric_energy
        public decimal? CurrentValleyElectricEnergy { get; set; } // Current_valley_electric_energy
        public DateTime? RecordTime { get; set; } // RecordTime
        public decimal? Communication { get; set; } // Communication
        public decimal? CommunicationBaudrate { get; set; } // CommunicationBaudrate
        public decimal? MonthTotalEnergy { get; set; } // MonthTotalEnergy
        public decimal? PeakMonthTotalEnergy { get; set; } // PeakMonthTotalEnergy
        public decimal? FlatMonthTotalEnergy { get; set; } // FlatMonthTotalEnergy
        public decimal? VolleyMonthTotalEnergy { get; set; } // VolleyMonthTotalEnergy
        public decimal? LastMonthTotalEnergy { get; set; } // LastMonthTotalEnergy
        public decimal? PeakLastMonthTotalEnergy { get; set; } // PeakLastMonthTotalEnergy
        public decimal? FlatLastMonthTotalEnergy { get; set; } // FlatLastMonthTotalEnergy
        public decimal? ValleyLastMonthTotalEnergy { get; set; } // ValleyLastMonthTotalEnergy
        public decimal? CurrentSpikeElectricEnergy { get; set; } // CurrentSpikeElectricEnergy
        public decimal? MonthSpikeEnergy { get; set; } // MonthSpikeEnergy
        public decimal? LastMonthSpikeEnergy { get; set; } // LastMonthSpikeEnergy
        
        public Adl300()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
