// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace ElecSales.Models
{
    // AllEnum
    public partial class AllEnum
    {
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 子Id判断是第几级菜单
        ///</summary>
        public int SubId { get; set; } // SubId

        ///<summary>
        /// 上级Id
        ///</summary>
        public int ParentId { get; set; } // ParentId

        ///<summary>
        /// 序列号(用于表示同级菜单位置)
        ///</summary>
        public int SerialNumber { get; set; } // SerialNumber

        ///<summary>
        /// 菜单图标
        ///</summary>
        public string Icon { get; set; } // Icon

        ///<summary>
        /// 菜单名称
        ///</summary>
        public string Title { get; set; } // Title

        ///<summary>
        /// 菜单关联的Controller
        ///</summary>
        public string Controller { get; set; } // Controller

        ///<summary>
        /// 菜单关联的Action
        ///</summary>
        public string Action { get; set; } // Action

        ///<summary>
        /// 是否删除
        ///</summary>
        public bool IsDelete { get; set; } // IsDelete

        ///<summary>
        /// 添加人
        ///</summary>
        public int CreateId { get; set; } // CreateId

        ///<summary>
        /// 添加时间
        ///</summary>
        public DateTime CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 菜单高级类型(0:对外  1:对内)
        ///</summary>
        public int Type { get; set; } // Type
        
        public AllEnum()
        {
            SubId = 0;
            SerialNumber = 0;
            IsDelete = false;
            Type = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
