// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace ElecSales.Models
{
    // Brokerage
    public partial class Brokerage
    {
        public int Id { get; set; } // Id (Primary key)
        public string Code { get; set; } // Code
        public int AgentId { get; set; } // AgentId
        public string AgentName { get; set; } // AgentName
        public int Reward { get; set; } // Reward
        public DateTime CreateTime { get; set; } // CreateTime
        public string ContractContent { get; set; } // ContractContent
        public int CreateId { get; set; } // CreateId
        public bool IsDelete { get; set; } // IsDelete
        public int ProjectId { get; set; } // ProjectId
        
        public Brokerage()
        {
            CreateTime = System.DateTime.Now;
            IsDelete = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
