// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace ElecSales.Models
{
    // ElectricityContract
    public partial class ElectricityContract
    {
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 合同编号
        ///</summary>
        public string Code { get; set; } // Code

        ///<summary>
        /// 合同类型
        ///</summary>
        public int Type { get; set; } // Type

        ///<summary>
        /// 电厂Id
        ///</summary>
        public int ElectricityFactoryId { get; set; } // ElectricityFactoryId

        ///<summary>
        /// 电量(Mwh/1000Kwh)
        ///</summary>
        public double ElectricityQuantity { get; set; } // ElectricityQuantity

        ///<summary>
        /// 电价
        ///</summary>
        public double Price { get; set; } // Price

        ///<summary>
        /// 开始周期
        ///</summary>
        public DateTime StartCycle { get; set; } // StartCycle

        ///<summary>
        /// 结束周期
        ///</summary>
        public DateTime EndCycle { get; set; } // EndCycle

        ///<summary>
        /// 合同内容
        ///</summary>
        public string ContractContent { get; set; } // ContractContent

        ///<summary>
        /// 添加人Id
        ///</summary>
        public int CreateId { get; set; } // CreateId

        ///<summary>
        /// 添加时间
        ///</summary>
        public DateTime CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 项目Id
        ///</summary>
        public int ProjectId { get; set; } // ProjectId
        public int? ContractState { get; set; } // ContractState
        public string CycleItemJson { get; set; } // CycleItemJson
        public bool IsDelete { get; set; } // IsDelete
        
        public ElectricityContract()
        {
            ContractState = 1;
            IsDelete = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
