// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace ElecSales.Models
{
    // ElectricityContractCycle
    public partial class ElectricityContractCycle
    {
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 周期
        ///</summary>
        public DateTime Cycle { get; set; } // Cycle

        ///<summary>
        /// 计划电量
        ///</summary>
        public double PlanNumber { get; set; } // PlanNumber

        ///<summary>
        /// 添加人
        ///</summary>
        public int CreateId { get; set; } // CreateId

        ///<summary>
        /// 添加时间
        ///</summary>
        public DateTime CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 合同Id
        ///</summary>
        public int ElectricityContractId { get; set; } // ElectricityContractId
        
        public ElectricityContractCycle()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
