// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace ElecSales.Models
{
    // ElectricityCompetitivePriceLog
    public partial class ElectricityCompetitivePriceLog
    {
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 价格梯度
        ///</summary>
        public decimal PriceGradient { get; set; } // PriceGradient

        ///<summary>
        /// 申报数量(Mwh)
        ///</summary>
        public double Number { get; set; } // Number

        ///<summary>
        /// 电力竞价方案Id
        ///</summary>
        public int ElectricityCompetitivePriceId { get; set; } // ElectricityCompetitivePriceId

        ///<summary>
        /// 添加人Id
        ///</summary>
        public int CreateId { get; set; } // CreateId

        ///<summary>
        /// 添加时间
        ///</summary>
        public DateTime CreateTime { get; set; } // CreateTime
        
        public ElectricityCompetitivePriceLog()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
