// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace ElecSales.Models
{
    // ElectricityFactory
    public partial class ElectricityFactory
    {
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 电厂名称
        ///</summary>
        public string Title { get; set; } // Title

        ///<summary>
        /// 电厂状态
        ///</summary>
        public int State { get; set; } // State

        ///<summary>
        /// 添加人Id
        ///</summary>
        public int CreateId { get; set; } // CreateId

        ///<summary>
        /// 添加时间
        ///</summary>
        public DateTime CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 项目Id
        ///</summary>
        public int ProjectId { get; set; } // ProjectId
        public string Remark { get; set; } // Remark
        public bool IsDelete { get; set; } // IsDelete
        public string Abbr { get; set; } // Abbr
        public string AddressDetail { get; set; } // AddressDetail
        public string Province { get; set; } // Province
        public string City { get; set; } // City
        public string Tel { get; set; } // Tel
        public int? YearTotal { get; set; } // YearTotal
        public int? EnterpriseCategory { get; set; } // EnterpriseCategory
        public string Code { get; set; } // Code
        public string AdministrativeRegion { get; set; } // AdministrativeRegion
        public string CorpOfCode { get; set; } // CorpOfCode
        public string CorpOfPerson { get; set; } // CorpOfPerson
        public string CorpOfIdCard { get; set; } // CorpOfIdCard
        public string CorpOfTaxCode { get; set; } // CorpOfTaxCode
        public string AccountBank { get; set; } // AccountBank
        public string AccountNumber { get; set; } // AccountNumber
        
        public ElectricityFactory()
        {
            IsDelete = false;
            YearTotal = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
