// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace ElecSales.Models
{
    // EnterpriseInfo
    public partial class EnterpriseInfo
    {
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 企业代码
        ///</summary>
        public string Code { get; set; } // Code

        ///<summary>
        /// 企业名称
        ///</summary>
        public string Title { get; set; } // Title

        ///<summary>
        /// 企业简称
        ///</summary>
        public string TitleAbbreviation { get; set; } // TitleAbbreviation

        ///<summary>
        /// 所属省级
        ///</summary>
        public string BelongProvinceArea { get; set; } // BelongProvinceArea

        ///<summary>
        /// 所属地级
        ///</summary>
        public string BelongArea { get; set; } // BelongArea

        ///<summary>
        /// 行政区域
        ///</summary>
        public string AdministrativeRegion { get; set; } // AdministrativeRegion

        ///<summary>
        /// 企业性质(国企,私营,外资,合资,其他)
        ///</summary>
        public int Category { get; set; } // Category

        ///<summary>
        /// 行业分类
        ///</summary>
        public string IndustryClassification { get; set; } // IndustryClassification

        ///<summary>
        /// 状态
        ///</summary>
        public int State { get; set; } // State

        ///<summary>
        /// 注册地址
        ///</summary>
        public string RegisteredAddress { get; set; } // RegisteredAddress

        ///<summary>
        /// 联系方式
        ///</summary>
        public string Contact { get; set; } // Contact

        ///<summary>
        /// 传真
        ///</summary>
        public string Fax { get; set; } // Fax

        ///<summary>
        /// 邮政编码
        ///</summary>
        public string ZipCode { get; set; } // ZipCode

        ///<summary>
        /// 企业所在地
        ///</summary>
        public string Located { get; set; } // Located

        ///<summary>
        /// 负荷性质
        ///</summary>
        public int LoadNature { get; set; } // LoadNature

        ///<summary>
        /// 所有制
        ///</summary>
        public string Ownership { get; set; } // Ownership

        ///<summary>
        /// 工商行政管理局
        ///</summary>
        public string AdministrationForIndustryAndCommerce { get; set; } // AdministrationForIndustryAndCommerce

        ///<summary>
        /// 组织机构代码
        ///</summary>
        public string OrganizationCode { get; set; } // OrganizationCode

        ///<summary>
        /// 开户名称
        ///</summary>
        public string AccountName { get; set; } // AccountName

        ///<summary>
        /// 开户银行
        ///</summary>
        public string AccountBank { get; set; } // AccountBank

        ///<summary>
        /// 开户账号
        ///</summary>
        public string Account { get; set; } // Account

        ///<summary>
        /// 税务登记号
        ///</summary>
        public string TaxRegistrationNumber { get; set; } // TaxRegistrationNumber

        ///<summary>
        /// 法定代表人
        ///</summary>
        public string TheLegalRepresentative { get; set; } // TheLegalRepresentative

        ///<summary>
        /// 法定代表人身份证号
        ///</summary>
        public string TheLegalRepresentativeIdCard { get; set; } // TheLegalRepresentativeIdCard

        ///<summary>
        /// 企业基本设施LogId
        ///</summary>
        public int? EnterpriseBaseFacilitiesLogId { get; set; } // EnterpriseBaseFacilitiesLogId

        ///<summary>
        /// 添加人Id
        ///</summary>
        public int CreateId { get; set; } // CreateId

        ///<summary>
        /// 添加时间
        ///</summary>
        public DateTime CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 项目Id
        ///</summary>
        public int ProjectId { get; set; } // ProjectId

        ///<summary>
        /// 企业户名
        ///</summary>
        public string EnterpriseAccountName { get; set; } // EnterpriseAccountName

        ///<summary>
        /// 企业户号
        ///</summary>
        public string EnterpriseAccountCode { get; set; } // EnterpriseAccountCode

        ///<summary>
        /// 户名简称
        ///</summary>
        public string SimpleAccountName { get; set; } // SimpleAccountName

        ///<summary>
        /// 地址
        ///</summary>
        public string Address { get; set; } // Address

        ///<summary>
        /// 电压等级
        ///</summary>
        public string VoltageLevel { get; set; } // VoltageLevel

        ///<summary>
        /// 用电总容量
        ///</summary>
        public string ElectricityCapacity { get; set; } // ElectricityCapacity

        ///<summary>
        /// 变电器容量
        ///</summary>
        public string TransformerCapacity { get; set; } // TransformerCapacity

        ///<summary>
        /// 单位产值能耗
        ///</summary>
        public string EnergyConsumption { get; set; } // EnergyConsumption

        ///<summary>
        /// 装机容量
        ///</summary>
        public string InstalledCapacity { get; set; } // InstalledCapacity

        ///<summary>
        /// 年用电量
        ///</summary>
        public string AnnualElectricityConsumption { get; set; } // AnnualElectricityConsumption
        
        public EnterpriseInfo()
        {
            Category = 0;
            State = 0;
            LoadNature = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
