// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace ElecSales.Models
{
    // EnterpriseInfo
    public partial class EnterpriseInfoConfiguration : EntityTypeConfiguration<EnterpriseInfo>
    {
        public EnterpriseInfoConfiguration()
            : this("dbo")
        {
        }
 
        public EnterpriseInfoConfiguration(string schema)
        {
            ToTable(schema + ".EnterpriseInfo");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName("Id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.Code).HasColumnName("Code").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.Title).HasColumnName("Title").IsRequired().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.TitleAbbreviation).HasColumnName("TitleAbbreviation").IsOptional().HasColumnType("nvarchar").HasMaxLength(100);
            Property(x => x.BelongProvinceArea).HasColumnName("BelongProvinceArea").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.BelongArea).HasColumnName("BelongArea").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.AdministrativeRegion).HasColumnName("AdministrativeRegion").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.Category).HasColumnName("Category").IsRequired().HasColumnType("int");
            Property(x => x.IndustryClassification).HasColumnName("IndustryClassification").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.State).HasColumnName("State").IsRequired().HasColumnType("int");
            Property(x => x.RegisteredAddress).HasColumnName("RegisteredAddress").IsOptional().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.Contact).HasColumnName("Contact").IsOptional().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.Fax).HasColumnName("Fax").IsOptional().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.ZipCode).HasColumnName("ZipCode").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.Located).HasColumnName("Located").IsOptional().HasColumnType("nvarchar").HasMaxLength(100);
            Property(x => x.LoadNature).HasColumnName("LoadNature").IsRequired().HasColumnType("int");
            Property(x => x.Ownership).HasColumnName("Ownership").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.AdministrationForIndustryAndCommerce).HasColumnName("AdministrationForIndustryAndCommerce").IsRequired().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.OrganizationCode).HasColumnName("OrganizationCode").IsRequired().HasColumnType("nvarchar").HasMaxLength(100);
            Property(x => x.AccountName).HasColumnName("AccountName").IsOptional().HasColumnType("nvarchar").HasMaxLength(100);
            Property(x => x.AccountBank).HasColumnName("AccountBank").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.Account).HasColumnName("Account").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.TaxRegistrationNumber).HasColumnName("TaxRegistrationNumber").IsOptional().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.TheLegalRepresentative).HasColumnName("TheLegalRepresentative").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.TheLegalRepresentativeIdCard).HasColumnName("TheLegalRepresentativeIdCard").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.EnterpriseBaseFacilitiesLogId).HasColumnName("EnterpriseBaseFacilitiesLogId").IsOptional().HasColumnType("int");
            Property(x => x.CreateId).HasColumnName("CreateId").IsRequired().HasColumnType("int");
            Property(x => x.CreateTime).HasColumnName("CreateTime").IsRequired().HasColumnType("datetime");
            Property(x => x.ProjectId).HasColumnName("ProjectId").IsRequired().HasColumnType("int");
            Property(x => x.EnterpriseAccountName).HasColumnName("EnterpriseAccountName").IsOptional().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.EnterpriseAccountCode).HasColumnName("EnterpriseAccountCode").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.SimpleAccountName).HasColumnName("SimpleAccountName").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.Address).HasColumnName("Address").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.VoltageLevel).HasColumnName("VoltageLevel").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.ElectricityCapacity).HasColumnName("ElectricityCapacity").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.TransformerCapacity).HasColumnName("TransformerCapacity").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.EnergyConsumption).HasColumnName("EnergyConsumption").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.InstalledCapacity).HasColumnName("InstalledCapacity").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.AnnualElectricityConsumption).HasColumnName("AnnualElectricityConsumption").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
