// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace ElecSales.Models
{
    public interface IDbEntities : IDisposable
    {
        DbSet<AccountClaims> AccountClaims { get; set; } // AccountClaims
        DbSet<AccountForRole> AccountForRole { get; set; } // AccountForRole
        DbSet<AccountLoginRelation> AccountLoginRelation { get; set; } // AccountLoginRelation
        DbSet<AccountRoles> AccountRoles { get; set; } // AccountRoles
        DbSet<Accounts> Accounts { get; set; } // Accounts
        DbSet<Adl100> Adl100 { get; set; } // ADL100
        DbSet<Adl300> Adl300 { get; set; } // ADL300
        DbSet<Adl3000> Adl3000 { get; set; } // ADL3000
        DbSet<Agents> Agents { get; set; } // Agents
        DbSet<AgentsLog> AgentsLog { get; set; } // AgentsLog
        DbSet<AllEnum> AllEnum { get; set; } // AllEnum
        DbSet<Brokerage> Brokerage { get; set; } // Brokerage
        DbSet<BrokerageLog> BrokerageLog { get; set; } // BrokerageLog
        DbSet<ContractTemplate> ContractTemplate { get; set; } // ContractTemplate
        DbSet<ContractTemplateLog> ContractTemplateLog { get; set; } // ContractTemplateLog
        DbSet<ElectricityCompetitivePrice> ElectricityCompetitivePrice { get; set; } // ElectricityCompetitivePrice
        DbSet<ElectricityCompetitivePriceLog> ElectricityCompetitivePriceLog { get; set; } // ElectricityCompetitivePriceLog
        DbSet<ElectricityContract> ElectricityContract { get; set; } // ElectricityContract
        DbSet<ElectricityContractCycle> ElectricityContractCycle { get; set; } // ElectricityContractCycle
        DbSet<ElectricityContractLog> ElectricityContractLog { get; set; } // ElectricityContractLog
        DbSet<ElectricityFactory> ElectricityFactory { get; set; } // ElectricityFactory
        DbSet<ElectricityFactoryLog> ElectricityFactoryLog { get; set; } // ElectricityFactoryLog
        DbSet<EnterpriseInfo> EnterpriseInfo { get; set; } // EnterpriseInfo
        DbSet<EnterpriseInfoAttachment> EnterpriseInfoAttachment { get; set; } // EnterpriseInfoAttachment
        DbSet<EnterpriseLog> EnterpriseLog { get; set; } // EnterpriseLog
        DbSet<Privileges> Privileges { get; set; } // Privileges
        DbSet<Project> Project { get; set; } // Project
        DbSet<ProjectEnumPrivileges> ProjectEnumPrivileges { get; set; } // ProjectEnumPrivileges
        DbSet<ProjectLog> ProjectLog { get; set; } // ProjectLog
        DbSet<ProjectRole> ProjectRole { get; set; } // ProjectRole
        DbSet<ProjectRoleEnum> ProjectRoleEnum { get; set; } // ProjectRoleEnum
        DbSet<RoleForPrivileges> RoleForPrivileges { get; set; } // RoleForPrivileges
        DbSet<SaleElectricityLog> SaleElectricityLog { get; set; } // SaleElectricityLog
        DbSet<SalesElectricity> SalesElectricity { get; set; } // SalesElectricity
        DbSet<SalesElectricityCycle> SalesElectricityCycle { get; set; } // SalesElectricityCycle
        DbSet<TransactionCategory> TransactionCategory { get; set; } // TransactionCategory

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(CancellationToken cancellationToken);
        
        // Stored Procedures
    }

}
// </auto-generated>
