// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace ElecSales.Models
{
    // Privileges
    public partial class Privileges
    {
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 名称
        ///</summary>
        public string Title { get; set; } // Title

        ///<summary>
        /// 菜单Id
        ///</summary>
        public int EnumId { get; set; } // EnumId

        ///<summary>
        /// 是否删除
        ///</summary>
        public bool IsDelete { get; set; } // IsDelete

        ///<summary>
        /// 添加人
        ///</summary>
        public int CreateId { get; set; } // CreateId

        ///<summary>
        /// 添加时间
        ///</summary>
        public DateTime CreateTime { get; set; } // CreateTime
        public string Controller { get; set; } // Controller
        public string Action { get; set; } // Action
        public string ClassString { get; set; } // ClassString
        public string Icon { get; set; } // Icon

        ///<summary>
        /// 按钮类型
        ///</summary>
        public int Type { get; set; } // Type

        ///<summary>
        /// 特殊权限(一个权限对应多个按钮)
        ///</summary>
        public bool IsSpecial { get; set; } // IsSpecial

        ///<summary>
        /// 特殊按钮关联父Id
        ///</summary>
        public int ParentId { get; set; } // ParentId
        
        public Privileges()
        {
            EnumId = 0;
            IsDelete = false;
            Controller = "N'javascript:'";
            Action = "N'void(0)'";
            Type = 0;
            IsSpecial = false;
            ParentId = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
