// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace ElecSales.Models
{
    // RoleForPrivileges
    public partial class RoleForPrivileges
    {
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 角色Id
        ///</summary>
        public int ProjectRoleId { get; set; } // ProjectRoleId

        ///<summary>
        /// 权限Id
        ///</summary>
        public int PrivilegeId { get; set; } // PrivilegeId
        
        public RoleForPrivileges()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
