// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace ElecSales.Models
{
    // SalesElectricity
    public partial class SalesElectricity
    {
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 合同编号
        ///</summary>
        public string Code { get; set; } // Code

        ///<summary>
        /// 合同类型
        ///</summary>
        public int Type { get; set; } // Type

        ///<summary>
        /// 客户Id
        ///</summary>
        public int EnterPriseId { get; set; } // EnterPriseId

        ///<summary>
        /// 电量(Mwh)
        ///</summary>
        public double ElectricityQuantity { get; set; } // ElectricityQuantity

        ///<summary>
        /// 电价
        ///</summary>
        public double Price { get; set; } // Price

        ///<summary>
        /// 偏差
        ///</summary>
        public int Deviation { get; set; } // Deviation

        ///<summary>
        /// 开始周期
        ///</summary>
        public DateTime StartCycle { get; set; } // StartCycle

        ///<summary>
        /// 结束周期
        ///</summary>
        public DateTime EndCycle { get; set; } // EndCycle

        ///<summary>
        /// 合同内容
        ///</summary>
        public string ContractContent { get; set; } // ContractContent

        ///<summary>
        /// 合同状态
        ///</summary>
        public int SaleContractState { get; set; } // SaleContractState

        ///<summary>
        /// 添加时间
        ///</summary>
        public DateTime CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 添加人
        ///</summary>
        public int CreateId { get; set; } // CreateId

        ///<summary>
        /// 周期内电力分配
        ///</summary>
        public string CycleItemJson { get; set; } // CycleItemJson

        ///<summary>
        /// 项目ID
        ///</summary>
        public int ProjectId { get; set; } // ProjectId

        ///<summary>
        /// 是否删除
        ///</summary>
        public bool IsDelete { get; set; } // IsDelete
        
        public SalesElectricity()
        {
            SaleContractState = 0;
            ProjectId = 0;
            IsDelete = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
