// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace ElecSales.Models
{
    // SalesElectricityCycle
    public partial class SalesElectricityCycle
    {
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 周期
        ///</summary>
        public DateTime Cycle { get; set; } // Cycle

        ///<summary>
        /// 电量
        ///</summary>
        public double ElectricityNumber { get; set; } // ElectricityNumber

        ///<summary>
        /// 售电合同Id
        ///</summary>
        public int SalesElectricityId { get; set; } // SalesElectricityId
        
        public SalesElectricityCycle()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
