// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace ElecSales.Models
{
    // TransactionCategory
    public partial class TransactionCategory
    {
        public int Id { get; set; } // Id (Primary key)
        public int ContractType { get; set; } // ContractType
        public string Name { get; set; } // Name
        public int ProjectId { get; set; } // ProjectId
        public int CreateId { get; set; } // CreateId
        public DateTime CreateTime { get; set; } // CreateTime
        public bool IsDelete { get; set; } // IsDelete
        public string Remark { get; set; } // Remark
        
        public TransactionCategory()
        {
            ContractType = 0;
            CreateTime = System.DateTime.Now;
            IsDelete = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
